version: '3.9'

services:
  api:
    build: api_app
    restart: always
    container_name: api
    expose:
      - "8000"
    entrypoint: [ "gunicorn", "src.main:app", "--workers", "4", "--worker-class",
                  "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--reload" ]
    env_file:
      - api_app/src/core/.env.dev
    depends_on:
      - kafka-1
      - kafka-2
    healthcheck:
      test: nc -z kafka-1 9092 || nc -z kafka-2 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - api

  etl:
    build: etl
    restart: always
    container_name: etl
    env_file:
      - etl/.env
    command: python src/main.py
    depends_on:
      - clickhouse-node1
      - clickhouse-node2
      - clickhouse-node3
      - clickhouse-node4
      - kafka-1
      - kafka-2
    healthcheck:
      test: nc -z kafka-1 9092 || nc -z kafka-2 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10

  zookeeper-ch:
    image: zookeeper:3.5
    container_name: zookeeper-ch
    hostname: zookeeper-ch

  clickhouse-node1:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    expose:
      - "8123"
      - "9000"
    volumes:
      - ./clickhouse_data/node1:/etc/clickhouse-server
    depends_on:
      - zookeeper-ch

  clickhouse-node2:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./clickhouse_data/node2:/etc/clickhouse-server
    depends_on:
      - zookeeper-ch

  clickhouse-node3:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node3
    hostname: clickhouse-node3
    volumes:
      - ./clickhouse_data/node3:/etc/clickhouse-server
    depends_on:
      - zookeeper-ch

  clickhouse-node4:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse-node4
    hostname: clickhouse-node4
    volumes:
      - ./clickhouse_data/node4:/etc/clickhouse-server
    depends_on:
      - zookeeper-ch

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    expose:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    expose:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
